# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", 'releases/**' ]
  pull_request:
    branches: [ "main", 'releases/**' ]
env:
  SOLUTION_PATH: ./DevShop.sln
  CONFIGURATION: Release
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Install MAUI Android Workload
      run: dotnet workload install maui-android --skip-manifest

    - name: Install MAUI iOS Workload
      run: dotnet workload install maui-ios --skip-manifest
    
    - name: Restore NuGet Packages
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build Solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore
    
    - name: Execute Test
      run: dotnet test ${{ env.SOLUTION_PATH }} --no-restore --no-build --verbosity normal
